#spring.application.name=demo


server:
port: 7070
spring:
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
#    datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username:
#    password:
datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username:
  password:
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.H2Dialect

##    lombok
#lombok:
#  log:
#    enabled: true
